name: password_manager
description: Example of simple Password Manager.
author: Roman Cinis
repository: https://github.com/tsinis/password_manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-224 <3.0.0"
  flutter: ">=1.23.0-14.0.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage:
     git:
       url: https://github.com/SteveAlexander/flutter_secure_storage.git
  pin_input_text_field: ^4.0.0-nullsafety.1
  sqflite_sqlcipher: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter:
  uses-material-design: true